-- Made changes using Supabase UI but `supabase db diff --linked` couldn't retrieve changes made
UPDATE item SET name='bicycle pump', variant_name=null, initial_quantity=7, quantity_metric=null WHERE id=1;
UPDATE item SET name='hiking bag', variant_name=null, initial_quantity=6, quantity_metric=null WHERE id=6;
UPDATE item SET name='compass housing', variant_name=null, initial_quantity=12, quantity_metric=null WHERE id=11;
UPDATE item SET name='compass mini', variant_name='new', initial_quantity=8, quantity_metric=null WHERE id=12;
UPDATE item SET name='groundsheet', variant_name='new', initial_quantity=41, quantity_metric=null WHERE id=16;
UPDATE item SET name='groundsheet', variant_name='old', initial_quantity=15, quantity_metric=null WHERE id=17;
UPDATE item SET name='Adventure', variant_name=null, initial_quantity=31, quantity_metric=null WHERE id=38;
UPDATE item SET name='Christian Education', variant_name=null, initial_quantity=28, quantity_metric=null WHERE id=43;
UPDATE item SET name='Citizenship', variant_name=null, initial_quantity=23, quantity_metric=null WHERE id=44;
UPDATE item SET name='Community Service', variant_name=null, initial_quantity=23, quantity_metric=null WHERE id=45;
UPDATE item SET name='Drill', variant_name=null, initial_quantity=19, quantity_metric=null WHERE id=47;
UPDATE item SET name='Drummer''s', variant_name=null, initial_quantity=19, quantity_metric=null WHERE id=48;
UPDATE item SET name='First Aid', variant_name=null, initial_quantity=39, quantity_metric=null WHERE id=51;
UPDATE item SET name='Hobbies', variant_name=null, initial_quantity=26, quantity_metric=null WHERE id=53;
UPDATE item SET name='Intermediate Proficiency Award (IPA)', variant_name=null, initial_quantity=22, quantity_metric=null WHERE id=54;
UPDATE item SET name='Kayaking', variant_name=null, initial_quantity=39, quantity_metric=null WHERE id=56;
UPDATE item SET name='Leadership (NCO Star)', variant_name=null, initial_quantity=23, quantity_metric=null WHERE id=57;
UPDATE item SET name='One Year Service', variant_name=null, initial_quantity=45, quantity_metric=null WHERE id=64;
UPDATE item SET name='Piper''s', variant_name=null, initial_quantity=18, quantity_metric=null WHERE id=65;
UPDATE item SET name='Cloth', variant_name='Stage 2', initial_quantity=49, quantity_metric=null WHERE id=70;
UPDATE item SET name='Swimming', variant_name=null, initial_quantity=29, quantity_metric=null WHERE id=72;
UPDATE item SET name='Target', variant_name=null, initial_quantity=38, quantity_metric=null WHERE id=73;
UPDATE item SET name='Total Defence', variant_name='Bronze', initial_quantity=8, quantity_metric=null WHERE id=75;
UPDATE item SET name='chevron', variant_name='PTE', initial_quantity=63, quantity_metric=null WHERE id=78;
UPDATE item SET name='chevron', variant_name='LCP', initial_quantity=35, quantity_metric=null WHERE id=79;
UPDATE item SET name='chevron', variant_name='CPL', initial_quantity=28, quantity_metric=null WHERE id=80;
UPDATE item SET name='chevron', variant_name='SGT', initial_quantity=23, quantity_metric=null WHERE id=81;
UPDATE item SET name='chevron', variant_name='SSG', initial_quantity=23, quantity_metric=null WHERE id=82;
UPDATE item SET name='crest', variant_name='WO', initial_quantity=13, quantity_metric=null WHERE id=88;
UPDATE item SET name='field rank', variant_name='LCP', initial_quantity=30, quantity_metric=null WHERE id=89;
UPDATE item SET name='field rank', variant_name='CPL', initial_quantity=33, quantity_metric=null WHERE id=90;
UPDATE item SET name='field rank', variant_name='SGT', initial_quantity=28, quantity_metric=null WHERE id=91;
UPDATE item SET name='field rank', variant_name='SSG', initial_quantity=14, quantity_metric=null WHERE id=92;
UPDATE item SET name='field rank', variant_name='WO', initial_quantity=13, quantity_metric=null WHERE id=93;
UPDATE item SET name='anklet', variant_name='left', initial_quantity=10, quantity_metric=null WHERE id=94;
UPDATE item SET name='anklet', variant_name='right', initial_quantity=10, quantity_metric=null WHERE id=95;
UPDATE item SET name='belt', variant_name='new', initial_quantity=1, quantity_metric=null WHERE id=96;
UPDATE item SET name='belt', variant_name='old', initial_quantity=0, quantity_metric=null WHERE id=97;
UPDATE item SET name='boots', variant_name='size 6', initial_quantity=1, quantity_metric=null WHERE id=98;
UPDATE item SET name='boots', variant_name='size 7', initial_quantity=1, quantity_metric=null WHERE id=99;
UPDATE item SET name='boots', variant_name='size 8', initial_quantity=2, quantity_metric=null WHERE id=100;
UPDATE item SET name='boots', variant_name='size 9', initial_quantity=1, quantity_metric=null WHERE id=101;
UPDATE item SET name='boots', variant_name='size 10', initial_quantity=1, quantity_metric=null WHERE id=102;
UPDATE item SET name='cap badge', variant_name=null, initial_quantity=22, quantity_metric=null WHERE id=105;
UPDATE item SET name='cap (new)', variant_name='size S', initial_quantity=5, quantity_metric=null WHERE id=106;
UPDATE item SET name='cap (new)', variant_name='size M', initial_quantity=1, quantity_metric=null WHERE id=107;
UPDATE item SET name='cap (new)', variant_name='size L', initial_quantity=7, quantity_metric=null WHERE id=108;
UPDATE item SET name='cap (old)', variant_name='size S', initial_quantity=4, quantity_metric=null WHERE id=109;
UPDATE item SET name='cap (old)', variant_name='size M', initial_quantity=13, quantity_metric=null WHERE id=110;
UPDATE item SET name='cross belt', variant_name='new', initial_quantity=1, quantity_metric=null WHERE id=112;
UPDATE item SET name='glove (new)', variant_name='left', initial_quantity=9, quantity_metric=null WHERE id=115;
UPDATE item SET name='glove (new)', variant_name='right', initial_quantity=9, quantity_metric=null WHERE id=116;
UPDATE item SET name='haversack loop', variant_name=null, initial_quantity=8, quantity_metric=null WHERE id=119;
UPDATE item SET name='haversack slide', variant_name=null, initial_quantity=13, quantity_metric=null WHERE id=120;
UPDATE item SET name='NCO lanyard', variant_name='new', initial_quantity=25, quantity_metric=null WHERE id=121;
UPDATE item SET name='pants', variant_name='size 25', initial_quantity=2, quantity_metric=null WHERE id=123;
UPDATE item SET name='pants', variant_name='size 26', initial_quantity=3, quantity_metric=null WHERE id=124;
UPDATE item SET name='pants', variant_name='size 27', initial_quantity=3, quantity_metric=null WHERE id=125;
UPDATE item SET name='pants', variant_name='size 27', initial_quantity=3, quantity_metric=null WHERE id=126;
UPDATE item SET name='pants', variant_name='size 30', initial_quantity=1, quantity_metric=null WHERE id=129;
UPDATE item SET name='pants', variant_name='size 32', initial_quantity=3, quantity_metric=null WHERE id=131;
UPDATE item SET name='pants', variant_name='size 34', initial_quantity=2, quantity_metric=null WHERE id=133;
UPDATE item SET name='polo tee', variant_name='size 3XS', initial_quantity=1, quantity_metric=null WHERE id=136;
UPDATE item SET name='polo tee', variant_name='size 2XS', initial_quantity=1, quantity_metric=null WHERE id=137;
UPDATE item SET name='polo tee', variant_name='size XS', initial_quantity=1, quantity_metric=null WHERE id=138;
UPDATE item SET name='polo tee', variant_name='size S', initial_quantity=3, quantity_metric=null WHERE id=139;
UPDATE item SET name='polo tee', variant_name='size M', initial_quantity=2, quantity_metric=null WHERE id=140;
UPDATE item SET name='polo tee', variant_name='size L', initial_quantity=1, quantity_metric=null WHERE id=141;
UPDATE item SET name='shorts', variant_name='size M', initial_quantity=3, quantity_metric=null WHERE id=146;
UPDATE item SET name='shorts', variant_name='size L', initial_quantity=1, quantity_metric=null WHERE id=147;
UPDATE item SET name='uniform shirt', variant_name='size 13', initial_quantity=1, quantity_metric=null WHERE id=148;
UPDATE item SET name='uniform shirt', variant_name='size 14', initial_quantity=1, quantity_metric=null WHERE id=149;
UPDATE item SET name='uniform shirt', variant_name='size 15', initial_quantity=1, quantity_metric=null WHERE id=150;
UPDATE item SET name='uniform shirt', variant_name='size 16', initial_quantity=1, quantity_metric=null WHERE id=151;
UPDATE item SET name='uniform shirt', variant_name='size 18', initial_quantity=1, quantity_metric=null WHERE id=153;
UPDATE item SET name='uniform shirt', variant_name='size 20', initial_quantity=1, quantity_metric=null WHERE id=155;
UPDATE item SET name='glove (old)', variant_name='left', initial_quantity=20, quantity_metric=null WHERE id=156;
UPDATE item SET name='glove (old)', variant_name='right', initial_quantity=20, quantity_metric=null WHERE id=157;
UPDATE item SET name='chapteh', variant_name=null, initial_quantity=12, quantity_metric=null WHERE id=162;
UPDATE item SET name='cloth (acting)', variant_name=null, initial_quantity=19, quantity_metric=null WHERE id=163;
UPDATE item SET name='ice-cream sticks', variant_name='coloured (pack of 50)', initial_quantity=11, quantity_metric=null WHERE id=166;
UPDATE item SET name='chopstick', variant_name=null, initial_quantity=45, quantity_metric='pair' WHERE id=182;
UPDATE item SET name='gun lighter', variant_name=null, initial_quantity=2, quantity_metric=null WHERE id=187;
UPDATE item SET name='mess tin', variant_name=null, initial_quantity=72, quantity_metric=null WHERE id=193;
UPDATE item SET name='steel wool (metal sponge)', variant_name=null, initial_quantity=2, quantity_metric=null WHERE id=194;
UPDATE item SET name='spatula', variant_name=null, initial_quantity=2, quantity_metric=null WHERE id=198;
UPDATE item SET name='sponge', variant_name=null, initial_quantity=40, quantity_metric=null WHERE id=199;
UPDATE item SET name='tommy cooker', variant_name='new', initial_quantity=84, quantity_metric=null WHERE id=201;
UPDATE item SET name='tongs', variant_name='long', initial_quantity=15, quantity_metric=null WHERE id=203;
UPDATE item SET name='tongs', variant_name='short', initial_quantity=11, quantity_metric=null WHERE id=204;
UPDATE item SET name='crepe bandage', variant_name=null, initial_quantity=2, quantity_metric=null WHERE id=205;
UPDATE item SET name='first aid kit', variant_name=null, initial_quantity=7, quantity_metric=null WHERE id=206;
UPDATE item SET name='Little Anne dummy', variant_name=null, initial_quantity=2, quantity_metric=null WHERE id=207;
UPDATE item SET name='Nerf gun bullet', variant_name=null, initial_quantity=351, quantity_metric=null WHERE id=214;
UPDATE item SET name='A4 folder', variant_name='blue', initial_quantity=10, quantity_metric=null WHERE id=218;
UPDATE item SET name='A4 folder', variant_name='purple', initial_quantity=9, quantity_metric=null WHERE id=221;
UPDATE item SET name='A4 folder (old)', variant_name='blue', initial_quantity=18, quantity_metric=null WHERE id=223;
UPDATE item SET name='tape', variant_name='double-sided', initial_quantity=1, quantity_metric=null WHERE id=225;
UPDATE item SET name='pencil', variant_name=null, initial_quantity=40, quantity_metric=null WHERE id=235;
UPDATE item SET name='scissors', variant_name=null, initial_quantity=22, quantity_metric=null WHERE id=236;
UPDATE item SET name='Primer''s chrome belt buckle', variant_name=null, initial_quantity=0, quantity_metric=null WHERE id=242;
UPDATE item SET name='Primer''s cap badge', variant_name=null, initial_quantity=0, quantity_metric=null WHERE id=243;
UPDATE item SET name='Primer''s cap', variant_name='size S', initial_quantity=0, quantity_metric=null WHERE id=244;
UPDATE item SET name='Primer''s cap', variant_name='size M', initial_quantity=3, quantity_metric=null WHERE id=245;
UPDATE item SET name='Primer''s cap', variant_name='size L', initial_quantity=0, quantity_metric=null WHERE id=246;
UPDATE item SET name='Primer''s uniform shirt (short sleeve)', variant_name='size S', initial_quantity=0, quantity_metric=null WHERE id=247;
UPDATE item SET name='Primer''s uniform shirt (short sleeve)', variant_name='size M', initial_quantity=0, quantity_metric=null WHERE id=248;
UPDATE item SET name='Primer''s uniform shirt (short sleeve)', variant_name='size L', initial_quantity=0, quantity_metric=null WHERE id=249;
UPDATE item SET name='Primer''s uniform shirt', variant_name='size S', initial_quantity=0, quantity_metric=null WHERE id=250;
UPDATE item SET name='Primer''s uniform shirt', variant_name='size M', initial_quantity=0, quantity_metric=null WHERE id=251;
UPDATE item SET name='Primer''s uniform shirt', variant_name='size L', initial_quantity=0, quantity_metric=null WHERE id=252;
UPDATE item SET name='Primer''s lanyard', variant_name=null, initial_quantity=3, quantity_metric=null WHERE id=253;
UPDATE item SET name='Primer''s polo tee', variant_name='size XS', initial_quantity=0, quantity_metric=null WHERE id=254;
UPDATE item SET name='Primer''s polo tee', variant_name='size S', initial_quantity=0, quantity_metric=null WHERE id=255;
UPDATE item SET name='Primer''s polo tee', variant_name='size M', initial_quantity=0, quantity_metric=null WHERE id=256;
UPDATE item SET name='Primer''s polo tee', variant_name='size L', initial_quantity=0, quantity_metric=null WHERE id=257;
UPDATE item SET name='Primer''s polo tee', variant_name='XL', initial_quantity=0, quantity_metric=null WHERE id=258;
UPDATE item SET name='BB Mask', variant_name=null, initial_quantity=20, quantity_metric=null WHERE id=259;
UPDATE item SET name='basketball', variant_name=null, initial_quantity=2, quantity_metric=null WHERE id=267;
UPDATE item SET name='table tennis (ping pong) ball', variant_name=null, initial_quantity=207, quantity_metric=null WHERE id=271;
