CREATE TABLE item (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    quantity_metric TEXT NULL,
    description TEXT NULL
);

CREATE TABLE item_variant (
    item_id INTEGER NOT NULL REFERENCES item (id),
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NULL,
    initial_quantity INTEGER NOT NULL,
    current_quantity INTEGER NOT NULL
);

CREATE TABLE category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE item_category (
    item_id INTEGER NOT NULL REFERENCES item (id),
    category_id INTEGER NOT NULL REFERENCES category (id),
    PRIMARY KEY (item_id, category_id)
);

CREATE TABLE item_variant_category (
    item_variant_id INTEGER NOT NULL REFERENCES item_variant (id),
    category_id INTEGER NOT NULL REFERENCES category (id)
);

CREATE TABLE transaction (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author TEXT NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE location (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    description TEXT NULL
);

CREATE TABLE transaction_detail (
    transaction_id INTEGER NOT NULL REFERENCES transaction (id),
    item_variant_id INTEGER NOT NULL REFERENCES item_variant (id),
    quantity SMALLINT NOT NULL,
    from_location_id INTEGER NULL REFERENCES location (id),
    to_location_id INTEGER NULL REFERENCES location (id)
);

CREATE TABLE item_variant_location (
    item_variant_id INTEGER NOT NULL REFERENCES item_variant (id),
    location_id INTEGER NOT NULL REFERENCES location (id),
    quantity INTEGER NOT NULL,
    PRIMARY KEY (item_variant_id, location_id)
);
