name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fly auth
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - run: flyctl auth -t $FLY_API_TOKEN docker
      - run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - run: echo 'VERSION=${{ fromJson(env.PACKAGE_JSON).version }}' >> $GITHUB_ENV
      - run: docker build . -t "registry.fly.io/bb-room:${{ env.VERSION }}" --build-arg VITE_SUPABASE_URL=${{ vars.VITE_SUPABASE_URL }} --build-arg VITE_SUPABASE_ANON_KEY=${{ vars.VITE_SUPABASE_ANON_KEY }}
      - run: docker push "registry.fly.io/bb-room:${{ env.VERSION }}"
      - run: flyctl deploy --remote-only --image "registry.fly.io/bb-room:${{ env.VERSION }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
